
# =====================================================
# APPLICATION
# =====================================================
spring.application.name=PFE

server.port=8080


# =====================================================
# POSTGRESQL DATABASE
# =====================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/pfe_db
spring.datasource.username=postgres
spring.datasource.password=******* Utilisez Votre password *******

spring.datasource.driver-class-name=org.postgresql.Driver


# =====================================================
# JPA / HIBERNATE
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# =====================================================
# FILE UPLOAD
# =====================================================
app.upload.dir=uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# =====================================================
# EMAIL CONFIG
# =====================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=******* Utilisez Votre email *******
spring.mail.password=******* Utilisez Votre password *******

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# =====================================================
# JWT
# =====================================================
app.jwt.secret=******* Utilisez Votre secret *******
app.jwt.expiration=86400000


# =====================================================
# LOGGING (dev)
# =====================================================
logging.level.org.springframework.security=DEBUG
spring.docker.compose.enabled=false